-- SQL to set up the database for Derma-AI in Supabase

-- 1. Create profiles table (links to auth.users)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  email TEXT NOT NULL,
  display_name TEXT,
  photo_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  last_login_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Enable Row Level Security (RLS) on profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 3. Create scans table
CREATE TABLE IF NOT EXISTS public.scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL, -- Changed from UUID to TEXT to support Firebase UIDs
  image_url TEXT NOT NULL,
  condition TEXT NOT NULL,
  urgency TEXT NOT NULL,
  confidence TEXT NOT NULL,
  analysis JSONB, -- Added to store the full AI report
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Fix if table exists and has UUID type:
-- DROP POLICY IF EXISTS "Users can view their own scans." ON public.scans;
-- DROP POLICY IF EXISTS "Users can insert their own scans." ON public.scans;
-- DROP POLICY IF EXISTS "Users can delete their own scans." ON public.scans;
-- ALTER TABLE public.scans ALTER COLUMN user_id TYPE TEXT USING user_id::text;
-- ALTER TABLE public.scans DROP CONSTRAINT IF EXISTS scans_user_id_fkey;

-- 4. Enable RLS on scans
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;

-- 5. Policies for profiles
CREATE POLICY "Public profiles are viewable by everyone." ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile." ON public.profiles
  FOR INSERT WITH CHECK (auth.uid()::text = id::text);

CREATE POLICY "Users can update own profile." ON public.profiles
  FOR UPDATE USING (auth.uid()::text = id::text);

-- 6. Policies for scans
-- Note: auth.uid()::text is used because user_id is type TEXT
CREATE POLICY "Users can view their own scans." ON public.scans
  FOR SELECT USING (auth.uid()::text = user_id);

CREATE POLICY "Users can insert their own scans." ON public.scans
  FOR INSERT WITH CHECK (auth.uid()::text = user_id);

CREATE POLICY "Users can delete their own scans." ON public.scans
  FOR DELETE USING (auth.uid()::text = user_id);

-- 7. STORAGE SETUP
-- Create the scans bucket if it doesn't exist
INSERT INTO storage.buckets (id, name, public)
VALUES ('scans', 'scans', true)
ON CONFLICT (id) DO UPDATE SET public = true;

-- Allow authenticated users to upload to the scans bucket
CREATE POLICY "Allow authenticated uploads" ON storage.objects
FOR INSERT TO authenticated WITH CHECK (bucket_id = 'scans');

-- Allow public read access to the scans bucket
CREATE POLICY "Allow public read" ON storage.objects
FOR SELECT TO public USING (bucket_id = 'scans');

-- 8. Trigger for profile creation on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, email, display_name, photo_url)
  VALUES (new.id, new.email, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
